### ISSUE TITLE
Already tokenized text

### ISSUE THREAD

**Issue by e-anima** [patrickschur/stanford-nlp-tagger#3]
Is it possible to integrate the options for an already tokenized text?
It is mentioned here: https://nlp.stanford.edu/software/pos-tagger-faq.html#newline

**Comment by patrickschur** [comment]
Normally it should be possible to integrate the options but this needs some modifications. Right now the options are more or less hardcoded. You can find them on line `110` in `POSTagger.php`.

But if you ask me the documentation is not very helpful here (for me). Can you give me an example of how to use this? I've already tried the options from above, but I couldn't get it to work.

**Comment by e-anima** [comment]
You are right, I tested various strings "pre-tokenized" but i could not find out what syntax actually is needed.
I also created a stackoverflow question: https://stackoverflow.com/questions/48429447/stanford-nlp-use-already-tokenized-text

The main problem with the  stanford pos-tagger (when using the integrated tokenizer) is that it will tag a lot of stuff just wrong, like "www.google.de" will be tagged as a NOUN. In my opinion it should be unknown .
 
p.s i just wrote all of thos down in case if someone else "googles" this.

I will take a look at the coreNLP now. Maybe that will help me understand more.
https://stanfordnlp.github.io/CoreNLP/cmdline.html

**Comment by patrickschur** [comment]
@e-anima Have you made any progress?

**Comment by e-anima** [comment]
Sadly not :(
I have switched my strategy and have found some code that uses machine learning. So i startet writing my own pos tagger.

**Comment by patrickschur** [comment]
Too bad. :(
Good luck with your own pos tagger. :)
