### ISSUE TITLE
Always getting empty result 

### ISSUE THREAD

**Issue by dignizant** [patrickschur/stanford-nlp-tagger#4]
My code is $pos->tag("we nned php developer");
i always get array(0) { }  in output but no other errors are thrown. Any solutions?

ithink this is version problem but i am not find out please any help for me.

**Comment by patrickschur** [comment]
I assume you activated error messages? If not please do.
I was not able to reproduce your issue but I was able to get an empty string back insteadof an empty array. So maybe this will help you. 

Just delete your `stanford-postagger-2017-06-09` folder and extract it again (do not use Ctrl+Z). 
This helps me...

**Comment by dignizant** [comment]
Delete standford-postagger-2017-06-09 folder and again extract it but still this is not working,i always get empty result.please any other solution?

My java version is also 1.8+ and my php version is also 7.0+ then what is the issue.i am not able to find out because no any errors are thrown it gives only empty result.

**Comment by patrickschur** [comment]
Have you tried to activate the error messages?

**Comment by dignizant** [comment]
yes but no any error thrown

![image](https://user-images.githubusercontent.com/1559995/36090324-f6fbd1aa-1005-11e8-96f4-65b757fc7518.png)
return empty result after call this function in POSTagger.php file.before this function my all results are proper.

**Comment by patrickschur** [comment]
I'm sorry, but I have no idea why this isn't working. :(

**Comment by dignizant** [comment]
Actually, the problem is `stream_get_contents()` function always returns empty string.
I have also tried with `rewind($pipes[1])` but same it returns always empty.

What are possible reasons for that?
Any server settings needed for that? because in other server same code is working fine.
Can you please check this? If it works, it will make my day...
Thanks in advance!

**Comment by patrickschur** [comment]
Can you check your php.ini for any disabled functions and which operating system do you use?

**Comment by dignizant** [comment]
What function i have check in php.ini file please describe and CentOS Linux Operating System use.
Also i have checked my php.ini file settings but all are proper.

**Comment by patrickschur** [comment]
Look for functions like `proc_open`, `stream_get_contents` and `escapeshellcmd`.

**Comment by dignizant** [comment]
proc_open and escapeshellcmd  function runs properly only stream_get_contents function not run proper it gives always empty

**Comment by patrickschur** [comment]
I have no idea why stream_get_contents is empty. So sorry... :(
If you know how, you can try to debug your code...

**Comment by dignizant** [comment]
Can you please tell us how many RAM size is requirement for this stanford postagger?

**Comment by patrickschur** [comment]
This depends on the size of your text. 
For example the following code needs **less** than 100 MiB (PHP itself only 880 KiB):
```php
<?php

require 'vendor/autoload.php';

$pos = new \StanfordTagger\POSTagger();

var_dump($pos->tag('My dog also likes eating sausage.'));
```

**Comment by dignizant** [comment]
[hs_err_pid2561.log](https://github.com/patrickschur/stanford-nlp-tagger/files/1733400/hs_err_pid2561.log)
Also some time gives java run time error so i asked how many RAM or memory requirement

Error is : "There is insufficient memory for the Java Runtime Environment to continue. # Native memory allocation (mmap) failed to map 2555904 bytes for committing reserved memory. "
![image](https://user-images.githubusercontent.com/1559995/36337673-a3746730-13c1-11e8-87e2-f781975a023f.png)

**Comment by patrickschur** [comment]
Maybe [this](https://github.com/cossou/JasperPHP/issues/39) will help you.

**Comment by dignizant** [comment]
thanks this helps me

**Comment by afilina** [comment]
Can someone publish what "this" is, since the link is broken? I also want to fix empty output.

**Comment by afilina** [comment]
Since "this" is a broken link, perhaps my debugging approach will help someone:

- Open `vendor/patrickschur/stanford-nlp-tagger/src/StanfordTagger/POSTagger.php`, make sure it's writable.
- Find `$cmd = escapeshellcmd [...]`
- Get the runtime value of `$cmd`, which should start with `java -mx2g -cp [...]`
- Run this in the command line. You should now see any error messages from the underlying command.

**Comment by afilina** [comment]
Since the solution above points to a broken link, perhaps my debugging approach will help someone:

- Open `vendor/patrickschur/stanford-nlp-tagger/src/StanfordTagger/POSTagger.php.
- Find `$cmd = escapeshellcmd [...]`
- Get the runtime value of `$cmd`, which should start with `java -mx2g -cp [...]`
- Run it in the command line. You should now see any error messages from the underlying command.
