### ISSUE TITLE
Error 500 when setting outputformat

### ISSUE THREAD

**Issue by hanlintao** [patrickschur/stanford-nlp-tagger#6]
Hi!

I am working with this tool right now but whenever I add this line:

$pos->setOutputFormat(StanfordTagger::OUTPUT_FORMAT_XML);

I met a 500 error.

What might be the possible cause for this?

Thanks!

**Comment by patrickschur** [comment]
What do you mean with 500 error? Internal Server Error? That doesn't make sense to me...
Please check if you have the newest version installed and make sure you installed the POSTagger in the right directory.

What's the output of the following script?
```php
<?php

use StanfordTagger\POSTagger;
use StanfordTagger\StanfordTagger;

require 'vendor/autoload.php';

$pos = new POSTagger();

$pos->setOutputFormat(StanfordTagger::OUTPUT_FORMAT_XML);

var_dump($pos->tag('My dog also likes eating sausage.'));
```

**Comment by patrickschur** [comment]
Closed because of inactivity.
